services:
  receptify:
    image: hampcl/receptify:1.0.17
    container_name: receptify
    ports:
      - "3000:3000"
    env_file:
      - receptify.env
    volumes:
      - ./logs:/app/logs  # Cambia esto a una ruta absoluta

  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "80:80"      # Puerto para tráfico HTTP
      - "443:443"    # Puerto para tráfico HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
   
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "certbot certonly --webroot --webroot-path=/var/www/certbot --email tu-email@example.com --agree-tos --no-eff-email -d receptify.cl -d www.receptify.cl"

volumes:
  logs:
