name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-219-15-136.us-east-2.compute.amazonaws.com << EOF
            cd receptify  
            ls -la && mkdir logs
            git pull origin main
            # Variables de entorno
            declare -A env_vars
            env_vars["AWS_ACCESS_KEY_ID"]="${{ secrets.AWS_ACCESS_KEY_ID }}"
            env_vars["AWS_SECRET_ACCESS_KEY"]="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            env_vars["AWS_S3_BUCKET_NAME"]="${{ secrets.AWS_S3_BUCKET_NAME }}"

            # Actualizar o agregar variables al archivo .env
            for key in "\${!env_vars[@]}"; do
              if grep -q "^$key=" receptify.env; then
                sed -i "s|^$key=.*|$key=\${env_vars[\$key]}|" receptify.env
              else
                echo "$key=\${env_vars[\$key]}" >> receptify.env
              fi
            done
            docker-compose down
            docker-compose up -d --build
          EOF
