name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-219-15-136.us-east-2.compute.amazonaws.com << EOF
            cd receptify
            ls -la && mkdir -p logs
            git reset --hard
            git fetch
            git checkout ${{ github.sha }}
            
            # Agregar variables al final del archivo .env
            {
              echo ""
              echo "DATABASE_URL=${{ secrets.DATABASE_URL}}"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}"
              echo "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}"
              echo "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY}}"
            } >> receptify.env

            docker-compose down
            docker-compose up -d --build
          EOF
